services:
  - type: web
    name: taskit-official
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
