// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eohoxsgohpnxqeqobgzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvaG94c2dvaHBueHFlcW9iZ3pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjQ1NjIsImV4cCI6MjA2MjQ0MDU2Mn0.C6rM-5ht9M3us3L-HV6UTQV4nUF5WMFXSLbXLeeMZpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);